### ISSUE TITLE
Version 2.0.0.2 breaks DropDowns (Azure DevOps Server)

### ISSUE THREAD

**Issue by christianbumann** [TUCRAIL/AdoPipelineOverview#54]
With the newest version of the widget 2.0.0.2 it is required to reconfigure the widget.
It is not possible anymore to select any pipeline, branch and tags.
Even with a new widget it's not possible anymore.

![screen1](https://github.com/user-attachments/assets/630d37d6-1e43-48db-ac48-0c54e4646c75)
![screen2](https://github.com/user-attachments/assets/b1766b3a-894d-4ba6-be12-b1202e57de01)

**Comment by christianbumann** [comment]
Tested with Chrome, Firefox and Edge

**Comment by GABRIELNGBTUC** [comment]
Hello. Just a few questions as I have successfully tested migration on Azure DevOps service using both widgets configured 1.1.x and 1.2.x:

- Could I have the version of Azure DevOps Server you are using so that I can setup a test environment for it and check if there are any differences API wise with Azure DevOps Services?
- Are there any pipeline created for the project you are using the widget with?
- Do you have any of the following two permissions on the pipeline tab? 
![image](https://github.com/user-attachments/assets/7fc34923-9ea6-4a27-bdd4-1a85d674d8a1)
- When you go in the dev tools of your browser, in the network tab. Could you check the call to retrieve the build definitions (the url should look something like "https://hsotname/collection/project-guid/_apis/build/definitions?includeAllProperties=true
") and provided the response?
- If there are any errors in the console, please could you provide them?

**Comment by GABRIELNGBTUC** [comment]
Ok the issue was much more straightforward than I thought.

Using a DevOps Server 2022.0.1 I was able to reproduce it with the error "VssVersionOutOfRangeException". Basically, the azure-devops-extension-api package only supports api version 7.2 preview since their "2.218.0" while Server 2022 only supports apis up to 7.2.

I'll open an issue on their Github repository, see if an upgrade to 2022.2 works as a workaround and evaluate the work to migrate all calls using api clients from their library to creating my own.

**Comment by GABRIELNGBTUC** [comment]
I have confirmed that using Azure DevOps Server 2022.2 does fix the issue. Though for now I'll add a disclaimer in the description of the extension on the marketplace and start working on implementing custom api clients.

**Comment by GABRIELNGBTUC** [comment]
It should not be fixed.

The workaround was to fork the azure-devops-extension-api repository and replace all api-version queries to use 5.1 (to keep feature parity with the version 1.x of the widget) instead of the latest preview.

I rebuild the fork, published it and updated the extension to use that forked package.

I also confirmed on both Azure DevOps server and services that the api version used is indeed the 5.1.

**Comment by christianbumann** [comment]
@GABRIELNGBTUC  wow - thank you for the really really fast workaround 🤘

**Comment by christianbumann** [comment]
Just tested the latest version, it works again.
Many thanks again.
